addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"  % "0.11.0")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release" % "1.5.10")
addSbtPlugin("io.spray"           % "sbt-revolver"   % "0.9.1" )
addSbtPlugin("org.scalameta"      % "sbt-mdoc"       % "2.2.24")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.4.3" )
