addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"  % "0.10.0")
addSbtPlugin("com.geirsson"       % "sbt-ci-release" % "1.5.7" )
addSbtPlugin("io.spray"           % "sbt-revolver"   % "0.9.1" )
addSbtPlugin("org.scalameta"      % "sbt-mdoc"       % "2.2.23")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.4.3" )
