addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"     % "1.4.6" )
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo" % "0.10.0")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"       % "2.0.2" )
addSbtPlugin("io.spray"           % "sbt-revolver"  % "0.9.1" )
addSbtPlugin("org.scalameta"      % "sbt-mdoc"      % "2.2.14")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"  % "3.9.5" )
addSbtPlugin("pl.project13.scala" % "sbt-jmh"       % "0.4.0" )
